services:
  db:
    image: postgres:17-alpine
    container_name: biblioteca-digital-db
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - biblioteca_digital_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DATABASE_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  biblioteca_digital_postgres: